### ISSUE TITLE
PoC the wrapper as a Go program

### ISSUE THREAD

**Issue by rikatz** [kubernetes-sigs/iptables-wrappers#4]
As discussed, there's some willingness to have the wrapper as a go compiled program instead of a shell script.

I'm raising this issue so we can discuss:

* Approach
* iptables-wrapper installer should be ported to compile the program to multi-platform? 
* What's the expectation we have for a go/no go? (performance? size of the binary? maintenability? )

Others to be defined.

I'm raising this issue for myself and further discussions, per https://github.com/kubernetes/release/pull/2502

I don't expect this to be a "contract" of we converting the wrapper to go, but more as a test/study so we can decide if we should do it or not.

/sig network
/sig release
/kind feature

/assign

cc @danwinship @puerco

**Comment by danwinship** [comment]
> iptables-wrapper installer should be ported to compile the program to multi-platform?

Hm... Presumably the other binaries in the container (eg kube-proxy) would be for a single specific platform, so you can just have the iptables-wrapper be the same platform.

The need for multi-platform support makes me feel like it would be pointless to try to provide any sort of "releases" of the iptables-wrapper binary. We should just expect people to vendor the repo and build their own copy of the binary and then install that.

Since the binary version would really only be for distroless installs, it wouldn't need the "alternatives" logic; it would just always use the manual symlinks approach.

We could also simplify things by saying that the compiled/distroless version only works with kube 1.17 or later (or even kube 1.24 or later), and not include the pre-1.17 codepath.

> What's the expectation we have for a go/no go? (performance? size of the binary? maintenability? )

I can't imagine that either performance or size would end up being relevant. (Like, obviously it has to end up being faster and smaller than the shell-based version.) I guess maybe if it's written in golang then the runtime might be large enough to make it "big", but in that case we could just write it in C instead... it's not a very complicated program.

Even if it is in golang and bigger than the shell version plus dependencies, it could theoretically be worth using anyway, if it makes the installation simpler.

So anyway, "maintainability" is likely to be the deciding factor.

**Comment by rikatz** [comment]
/lifecycle active
Will return to this in 1.26 cycle

**Comment by BenTheElder** [comment]
This will need some follow-up for the distroless-iptables image https://github.com/kubernetes/release/tree/master/images/build/distroless-iptables

**Comment by BenTheElder** [comment]
Filed https://github.com/kubernetes/release/issues/2992 to track
